export const RESTAURANT_CUISINES: readonly string[] = [
  'grocery',
  'pizza',
  'sushi',
  'halal',
  'fast food',
  'burgers',
  'desserts',
  'indian',
  'poke',
  'korean',
  'asian',
  'healthy',
  'thai',
  'chinese',
  'bbq',
  'mexican',
  'wings',
  'italian',
  'soup',
  'ice cream',
  'bakery',
  'bubble tea',
  'breakfast',
  'comfort food',
  'vietnamese',
  'america',
  'sandwich',
  'greek',
  'vegan',
  'soul food',
  'seafood',
  'japanase',
  'hawaiian',
  'smoothies',
  'coffee',
  'kosher',
  'street food',
  'caribbean',
  'taiwanese',
  ];

export type RestaurantCuisine = (typeof RESTAURANT_CUISINES)[number];
